name: Main CI
   
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
   
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: git clone
        uses: actions/checkout@v2
   
     # - name: npm install
     #   run: npm install
   
     # - name: npm build
     #   run: npm run build
   
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run:
          aws s3 cp --recursive --region ap-northeast-2 config s3://leo-git-repo
  slack-notification:
    if: ${{ always() }}
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - name: Set CUSTOM_STATUS Env Variable
        run: |
          if [ "${{ needs.build.result }}" = "failure" ] || \
             [ "${{ needs.build.result }}" = "failure" ];
          then
            CUSTOM_STATUS="❌ 실패"
          elif [ "${{ needs.build.result }}" = "cancelled" ] || \
            [ "${{ needs.build.result }}" = "cancelled" ];
          then
            CUSTOM_STATUS="⚠️ 취소"
          else
            CUSTOM_STATUS="✅ 성공"
          fi
          
          echo "CUSTOM_STATUS=${CUSTOM_STATUS}" >> $GITHUB_ENV
          
      - name: slack-send
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: 'Confit upload complate'
          SLACK_TITLE: 'github action msg'
          SLACK_USERNAME: Leocom
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
